# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara/poltergeist'

require 'autopsy/cucumber'
require 'autopsy/poltergeist'

Capybara.configure do |config|
  config.run_server = false
  config.default_driver = :default_poltergeist_driver
  config.javascript_driver = :default_poltergeist_driver
  config.app_host = 'http://localhost:4200'

  config.default_selector = :css
  config.raise_server_errors = false
end

AutopsyPoltergeist.init(:default_poltergeist_driver, {
  js_errors: false,
  timeout: 380,
  phantomjs_logger: StringIO.new,
  logger: nil,
  phantomjs_options: ['--load-images=yes', '--ignore-ssl-errors=yes'],
  phantomjs:  Phantomjs.path,
  window_size: [1200, 1200]
})

ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Before do
  visit '/'
  page.execute_script('if (localStorage && localStorage.clear) localStorage.clear()')
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { :except => [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('~@no-txn', '~@selenium', '~@culerity', '~@celerity', '~@javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

